import { TitleSlide } from './TitleSlide';
import { BioSlide } from './BioSlide';
import { TimelineSlide } from './TimelineSlide';
import { ClaudeCodeSlide } from './ClaudeCodeSlide';
import { IntroSlide } from './IntroSlide';
import { EngineerSectionSlide } from './EngineerSectionSlide';
import { TeamSectionSlide } from './TeamSectionSlide';
import { WhatIsAiFirstTeamSlide } from './WhatIsAiFirstTeamSlide';
import { SdlcTracesSlide } from './SdlcTracesSlide';
import { PersonalAspirationSlide } from './PersonalAspirationSlide';
import { BreakOutOfCodingSlide } from './BreakOutOfCodingSlide';
import { OrgSectionSlide } from './OrgSectionSlide';
import { JuniorEngineerSlide } from './JuniorEngineerSlide';
import { DisclaimerSlide } from './DisclaimerSlide';
import { VibeFlowSlide } from './VibeFlowSlide';
import { ContextToolsSlide } from './ContextToolsSlide';
import { CodeSlopSlide } from './CodeSlopSlide';
import { ImportantSlide } from './ImportantSlide';
import { UltimateExampleSlide } from './UltimateExampleSlide';
import { SkillsAuthoringSlide } from './SkillsAuthoringSlide';
import { SkillFlywheelSlide } from './SkillFlywheelSlide';
import { SkillMarketplaceSlide } from './SkillMarketplaceSlide';
import { MetaSkillsSlide } from './MetaSkillsSlide';
import { SkillsActivatorSlide } from './SkillsActivatorSlide';
import { FinalSlide } from './FinalSlide';

export const slides = [TitleSlide, BioSlide, TimelineSlide, IntroSlide, ClaudeCodeSlide, EngineerSectionSlide, JuniorEngineerSlide, DisclaimerSlide, VibeFlowSlide, ContextToolsSlide, CodeSlopSlide, ImportantSlide, UltimateExampleSlide, TeamSectionSlide, WhatIsAiFirstTeamSlide, SdlcTracesSlide, PersonalAspirationSlide, BreakOutOfCodingSlide, SkillsAuthoringSlide, SkillFlywheelSlide, SkillMarketplaceSlide, MetaSkillsSlide, SkillsActivatorSlide, OrgSectionSlide, FinalSlide];
