import { TitleSlide } from './TitleSlide';
import { BioSlide } from './BioSlide';
import { TimelineSlide } from './TimelineSlide';
import { ClaudeCodeSlide } from './ClaudeCodeSlide';
import { IntroSlide } from './IntroSlide';
import { EngineerSectionSlide } from './EngineerSectionSlide';
import { TeamSectionSlide } from './TeamSectionSlide';
import { OrgSectionSlide } from './OrgSectionSlide';
import { JuniorEngineerSlide } from './JuniorEngineerSlide';
import { DisclaimerSlide } from './DisclaimerSlide';
import { LaunchSlide } from './LaunchSlide';
import { TryItSlide } from './TryItSlide';
import { VibeFlowSlide } from './VibeFlowSlide';
import { ContextToolsSlide } from './ContextToolsSlide';
import { CodeSlopSlide } from './CodeSlopSlide';
import { ImportantSlide } from './ImportantSlide';
import { LifeAfterCommitSlide } from './LifeAfterCommitSlide';
import { SavingsSlide } from './SavingsSlide';
import { SkillsAuthoringSlide } from './SkillsAuthoringSlide';
import { AIFirstRoleSlide } from './AIFirstRoleSlide';
import { AIFirstWorkflowSlide } from './AIFirstWorkflowSlide';
import { AIFirstToolsSlide } from './AIFirstToolsSlide';
import { FinalSlide } from './FinalSlide';

export const slides = [TitleSlide, BioSlide, TimelineSlide, IntroSlide, ClaudeCodeSlide, EngineerSectionSlide, JuniorEngineerSlide, DisclaimerSlide, VibeFlowSlide, ContextToolsSlide, LaunchSlide, TryItSlide, CodeSlopSlide, ImportantSlide, LifeAfterCommitSlide, SavingsSlide, SkillsAuthoringSlide, AIFirstRoleSlide, AIFirstWorkflowSlide, AIFirstToolsSlide, TeamSectionSlide, OrgSectionSlide, FinalSlide];
