import { TitleSlide } from './TitleSlide';
import { BioSlide } from './BioSlide';
import { ClaudeCodeSlide } from './ClaudeCodeSlide';
import { InstallSlide } from './InstallSlide';
import { IntroSlide } from './IntroSlide';
import { AgendaSlide } from './AgendaSlide';
import { BillionDollarSlide } from './BillionDollarSlide';
import { PeterMobileSlide } from './PeterMobileSlide';
import { JuniorEngineerSlide } from './JuniorEngineerSlide';
import { DisclaimerSlide } from './DisclaimerSlide';
import { TheorySlide } from './TheorySlide';
import { ContextSlide } from './ContextSlide';
import { ContextPrinciplesSlide } from './ContextPrinciplesSlide';
import { ClaudeMdSlide } from './ClaudeMdSlide';
import { McpSlide } from './McpSlide';
import { TheoryCompleteSlide } from './TheoryCompleteSlide';
import { ResearchSlide } from './ResearchSlide';
import { TechnicalSlide } from './TechnicalSlide';

export const slides = [TitleSlide, BioSlide, ClaudeCodeSlide, IntroSlide, AgendaSlide, InstallSlide, BillionDollarSlide, PeterMobileSlide, JuniorEngineerSlide, DisclaimerSlide, TheorySlide, ContextSlide, ContextPrinciplesSlide, ClaudeMdSlide, McpSlide, TheoryCompleteSlide, ResearchSlide, TechnicalSlide];
